### ISSUE TITLE
Release pipeline

### ISSUE THREAD

**Issue by johntdyer** [william20111/terraform-provider-thousandeyes#28]
Based on tags it appears our last release was in April and we've done a ton since then.   I think we need to get a proper pipeline to release to https://registry.terraform.io/

**Comment by william20111** [comment]
100% makes sense. Its closed beta just now so cant set it up will do so once its open beta or GA.

**Comment by william20111** [comment]
https://registry.terraform.io/providers/william20111/thousandeyes/latest done
