### ISSUE TITLE
assistance getting 3 open PRs pushed

### ISSUE THREAD

**Issue by johntdyer** [william20111/terraform-provider-thousandeyes#39]
@william20111  can you please help me get my three PR's out so I can cut a new release.  I have a minor presentation tomorrow for some teams and I'd like to demonstrate a TE managed account using idiomatic terraform, however these PR's are representative of the issues I encountered, eg a bunch of commented out code ;-P

**Comment by johntdyer** [comment]
Sorry, looks like just two, #34  and #35 at which point I would like to bump the go-thousandeyes to 1.1.1 to pick up my other changes.  If you want I can make a PR for that now or wait ?

**Comment by william20111** [comment]
Whoops just cut a release without the go.mod bump. Create a PR for that and ill merge and release another cut.

**Comment by johntdyer** [comment]
Thanks man, really appreciate it....  I really need to take the time to learn to get terraform to use local dev builds so I am nbot blocked on production releases... :)

**Comment by william20111** [comment]
all sorted
